from base_classes.coordinate import Coordinate

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
TURQUOISE = (64, 224, 208)

# Screen
SCREEN_HEIGHT = 700
SCREEN_WIDTH = 1000
FIELD_WIDTH = 1024
FIELD_HEIGHT = 600
MENU_WIDTH = 1024
MENU_HEIGHT = 100
MENU_BG_COLOR = TURQUOISE
MENU_NUM_BUTTON = 3
MENU_DIST_BUTTON = 50
TILESIZE_DEFAULT = Coordinate(32, 32)
BUTTON_HEIGHT = 50
BUTTON_WIDTH = 65

# Enemies
ENEMY_SIZE_DEFAULT = Coordinate(TILESIZE_DEFAULT.x - 7, TILESIZE_DEFAULT.y - 7)
ENEMY_LIFE_DEFAULT = 5
ENEMY_SPEED_DEFAULT = 3
ENEMY_SPAWN_EVENT = 1
ENEMY_SPAWN_DELAY = 200
ENEMY_MAX_WAVE = 3
ENEMY_WAVE_LEN = 5
ENEMY_COEFFICIENT = 1.6

GAME = None  # When the game created, the Game class will be stored there.
FONT = None
FONT_SIZE = 38
FPS = 60
TITLE = "Tower Defense"
WORLD1 = 'world1.txt'
WORLD_FOLDER = 'worlds'
MENU_FILE = 'menu'
IMG_FOLDER = 'images'
BUTTON_PATH = "buttons"
TOWER_FOLDER = 'towers'
TOWERS_FILE = 'tower.txt'
ASSETS = {}

ENEMY_COST = 200

TOWER_PRICE = 600
TOWER_DELAY_DEFAULT = 5
TOWER_DAMAGE_DEFAULT = 4
TOWER_RANGE_DEFAULT = 100
NEW_WAVE_BONUS = 500
CUSTOMER_MONEY = 1200
BULLET_SPEED_DEFAULT = 3
BULLET_SIZE_DEFAULT = Coordinate(x=5, y=5)
BULLET_IMAGE_DEFAULT = 'bullet.png'
